pub(crate) mod admitted_exclusive_object_pool;
pub(crate) mod admitted_host_object_cache;
pub(crate) mod admitted_pinned_runtime_actor_pool;
pub(crate) mod audio_frontend;
pub(crate) mod aux_pack_registry;
pub(crate) mod builtin_execution_dispatch;
pub mod candidate_activation_transaction;
pub mod cohere;
pub(crate) mod ctc_greedy_decode;
pub(crate) mod ctc_prefix_beam;
pub(crate) mod ctc_streaming_driver;
pub(crate) mod decode_policy_component_registry;
pub(crate) mod decode_token_history;
pub(crate) mod device_greedy_token;
pub(crate) mod diarize_pack_import;
pub(crate) mod dolphin;
pub(crate) mod executor_component_registry;
pub(crate) mod family_integration_audit;
#[cfg(test)]
mod family_source_gates;
pub(crate) mod fastconformer;
pub(crate) mod firered_aed;
pub(crate) mod firered_llm;
pub(crate) mod firered_punc;
pub(crate) mod frame_sync_streaming_driver;
pub(crate) mod frontend_component_registry;
pub(crate) mod funasr_nano;
pub mod ggml_asr_executor;
pub(crate) mod ggml_composed_executor;
pub mod ggml_family_adapter;
pub(crate) mod ggml_graph_config;
pub(crate) mod ggml_streaming_audio;
pub(crate) mod ggml_streaming_session;
pub(crate) mod gpt2_bpe;
pub(crate) mod granite_speech;
pub(crate) mod graph_runtime_config;
pub(crate) mod incremental_streaming_driver;
pub(crate) mod kaldi_fbank;
pub(crate) mod language;
pub(crate) mod local_source_import;
pub(crate) mod lora_adapter;
pub(crate) mod mapped_token_embedding;
pub(crate) mod mimo_asr;
pub mod moonshine;
pub(crate) mod moss_transcribe_diarize;
pub mod native_execution_services;
pub mod oasr_metadata;
pub(crate) mod pack_import_surface;
pub mod pack_quant;
pub mod pack_quant_audit;
pub mod pack_requant;
pub(crate) mod pack_verifier;
pub(crate) mod parakeet_ctc;
pub(crate) mod parakeet_runtime_memory;
pub mod parakeet_tdt;
pub(crate) mod phrase_bias_decode;
pub(crate) mod policy_resolved_aux_runtime;
pub(crate) mod prepared_runtime_cache;
pub(crate) mod pyannote;
pub mod qwen;
pub mod request_execution_receipt;
pub(crate) mod resident_owner;
#[cfg(test)]
mod resident_runtime_audit;
pub(crate) mod runtime_asset_bootstrap;
pub(crate) mod runtime_cache_coordinator;
pub(crate) mod runtime_component_bootstrap;
pub(crate) mod runtime_contract;
pub(crate) mod runtime_memory;
pub(crate) mod runtime_pack_contract;
pub(crate) mod runtime_preflight;
pub(crate) mod runtime_prepared_registry;
pub mod runtime_receipts;
pub(crate) mod runtime_selection_metadata;
pub(crate) mod runtime_tensor_contract_registry;
pub(crate) mod runtime_weight_component_registry;
pub(crate) mod safetensors_json;
pub(crate) mod sensevoice;
pub(crate) mod sentencepiece_word_timestamps;
pub(crate) mod seq2seq_decoder_state;
pub(crate) mod seq2seq_dtw_alignment;
pub(crate) mod seq2seq_greedy_decode;
mod seq2seq_serve_batch;
pub(crate) mod seq2seq_word_timestamps;
pub(crate) mod serve_batch_env;
pub(crate) mod spm_decoder;
#[cfg(test)]
mod streaming_finalize_bench;
pub(crate) mod streaming_partial_cadence;
pub(crate) mod system_memory_owner;
pub(crate) mod tensor_binding;
pub(crate) mod tensor_schema;
pub(crate) mod text_prefix;
pub(crate) mod tokenizer_component_registry;
pub(crate) mod wav2vec2_ctc;
pub mod whisper;
pub(crate) mod xasr_zipformer;

// xtask generated model-family modules begin
// xtask generated model-family modules end
